version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/lobsters:cached
      - /lobsters/.bundle
      - /lobsters/.gem
      - gem_cache:/lobsters/.gem
      - bundle_cache:/lobsters/.bundle
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: password
      MARIADB_HOST: db
      MARIADB_PASSWORD: password
      MARIADB_USER: root
      RAILS_ENV: development
  db:
    image: "mariadb:11"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lobsters_development
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
volumes:
  gem_cache:
  bundle_cache:
  db_data:
