services:
  web:
    image: "curated/lobsters:latest"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - RAILS_ENV=production 
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-$(openssl rand -hex 64)}
      - MARIADB_HOST=db
      - MARIADB_PORT=3306
      - MARIADB_PASSWORD=password  # 改用 MYSQL_ 前缀
      - MARIADB_USER=root
      - LOBSTER_DATABASE=lobsters
      - LOBSTER_SITE_NAME="Curated Town"
      - LOBSTER_HOSTNAME=curated.localhost
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EXCEPTION_SENDER_ADDRESS=${EXCEPTION_SENDER_ADDRESS}
      - EXCEPTION_RECIPIENTS=${EXCEPTION_RECIPIENTS}
      - MAILER_DELIVERY_METHOD=smtp
    restart: unless-stopped

  db:
    image: "mariadb:11"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: lobsters_production
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./.local/caddy-data:/data
      - ./.local/caddy-config:/config
    depends_on:
      - web

volumes:
  db_data:
